sudo: required

language: php

branches:
    only:
        - master
        - php7
        - php5
        - add-ci-build

notifications:
    slack:
        secure: WIRdJ6WeGxpI/MVcpao9VatooY6+93WC+OGyWoXBmMke/iAVlUIZFoEkxI1IPDQ/TLarcYoiOxmjX4JuO0nO3zL5MrNfKOr/KLKtiIyHG3Q9Dw96eHmvmO52Vtr29J+GTb6K/VTdNJsMfzlcyr89/U3FUqvE76u4+O/EpO4XSwtQhYek4RGROOcVu69NjtTIS73VHhDYRHZMTytx99LWE3be8xCa5hf9oaUL8WRVLblYDrJTE+aLAoJkE81bfeEXrBiPJf8lw+iIu6mFwleGDZnycBeyuLJp0GSJ+4qoYlOeCdxxjsx56Ib2vV5Qkx5sU3gSg6rVUEWyIW3Iz/z2Cpqk6qWRc+BTvsVHkwnN7RI29+0zxuikuf252y8e2XfZead9098P9ucmzsmnQxVhYKpmtgVcJ9oPAG4HnpylEUSUP3f1C6v482sKoh7+os82nBtLZEcRDqy1F3gAMov1M9+Tg6HyVPe/aAoszY854l0w3cFIs6YD7R8IBDikQ+GE9Zwp8s4HC/zlCx5qi55amPBHtApfgOOVCD4lSKxrXKL37OCRLIUmwUno2z1z/q5oiR5KY+INcrcXL84aRD4ix4YnNJXfELB71fWvTzP3rmS423E8UWz8hUUc2MwlcvdKe6NyBu9Sc8F+SIcHqgEd3qQtOBjOf8OMXmNpAd1tbXU=

services:
    - docker

before_install:
    - docker build -t mkenney/phpunit:ci-build .
    - cd test

script:
    - docker run --rm -ti -v $(pwd):/src:rw mkenney/phpunit:ci-build --version

#after_success:
#    - curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": $TRAVIS_BRANCH}' -X POST https://registry.hub.docker.com/u/mkenney/phpunit/trigger/6cfc768e-a07b-48c1-890c-24bbd071261c/
